### ISSUE TITLE
可否做到像天凤用户日志那样的功能？

### ISSUE THREAD

**Issue by EndlessCheng** [SAPikachu/amae-koromo#10]
这个牌谱爬虫看上去挺不错的，弥补了雀魂缺失的一些功能（相较于天凤）。

有了这些数据后，希望作者能添加更多功能，做出像 [天凤用户日志查询](https://nodocchi.moe/) 这样的统计结果。

**Comment by SAPikachu** [comment]
具体来说需要什么功能呢？全站复刻我可能不太够精力做，不过如果有什么有用的功能的话我可以看看能不能添加。

**Comment by EndlessCheng** [comment]
可以考虑加入排行榜中的功能，如 7 天内上升最快的玩家等。

另一个是一段时间范围内的 pt 变化，比如以天为单位，绘制折线图，感觉这个能反映玩家的水平变化。

这些功能旁可以添加分享链接，或许能让更多人知道这个项目。

**Comment by SAPikachu** [comment]
这两个功能都已经实装了。
