### ISSUE TITLE
是否可以授权使用接口或合作开发？

### ISSUE THREAD

**Issue by kamicloud** [SAPikachu/amae-koromo#11]
作者您好，我是“雀魂绝好调”微信小程序的开发者，雀魂绝好调整合了mahjong-helper的功能，提供了天凤牌理的牌效计算，并同步展示雀魂战绩排行榜。前后端均非盈利并且完全开源。

希望能由您授权，使用雀魂牌理屋的接口，或和您合作开发网页和小程序，两个工具技术栈比较重叠，都是ts+react。

如果您对此感兴趣，期望您的答复。

**Comment by SAPikachu** [comment]
可以的，开发初期你可以直接使用这边服务端的接口，有需要的话我可以给你加 CORS 白名单，如果后面流量过大的话我们再研究下怎么样处理。具体接口用法就需要你直接看代码研究了，我这边会尽可能保持接口稳定，但是也不能保证绝对不出现 breaking change 就是了。你的项目现在在 GitHub 吗？希望能先看看源代码~

**Comment by kamicloud** [comment]
https://github.com/kamicloud/mahjong-science-server
和
https://github.com/kamicloud/mahjong-science

只做了一些简单的功能，现在卡在解决前端资源文件映射的问题上了

感谢您的支持，因为上小程序，所以没有跨域问题

**Comment by SAPikachu** [comment]
嗯好的，看着没什么问题，这里就先 close 了，如果有什么需要的话就另外开新 issue 吧~
