### ISSUE TITLE
[Feature Request] Historical highest/lowest rank point

### ISSUE THREAD

**Issue by chezeji** [SAPikachu/amae-koromo#110]
Presently, only "Current rank point" is provided. I think it would a great idea to provide historical highest/lowest rank point within a time range. Thank you for considering the feature request.

**Comment by SAPikachu** [comment]
We already have highest rank/point on the page, I will consider lowest rank/point when I am available.
![image](https://github.com/user-attachments/assets/2afe8269-e92e-4b62-af5a-f7dced790289)
