### ISSUE TITLE
苦主/汪汪榜有个bug

### ISSUE THREAD

**Issue by CXY1999** [SAPikachu/amae-koromo#13]
刚才看了一下苦主/汪汪榜，有个豪一老哥升了豪二 从豪一2800多pt升段到豪二1600pt 系统给他判定为掉分 就上了苦主榜了……
这位玩家的ID：Noein5 
四周苦主榜目前末尾 实际看了一下这四周战绩他是从豪一打到了豪二 理论上讲应该是PT得分为正

**Comment by CXY1999** [comment]
不确定汪汪榜是否也存在这种情况  可能有往下掉段的一下子相当于莫名奇妙涨了几千pt

**Comment by SAPikachu** [comment]
刚刚看了下，这位现在已经不在苦主榜了，他是早上一波好调升段的，有可能是因为数据更新延迟所以你看的时候还没下榜。我看看能不能把更新频率加密一点。

**Comment by SAPikachu** [comment]
大概明白了，早上服务器出了一些问题导致排行榜没有更新。现在已经修复了。
