### ISSUE TITLE
能否做个役满公告

### ISSUE THREAD

**Issue by CXY1999** [SAPikachu/amae-koromo#15]
放在首页滚动比如某人和了役满就显示：
XXX荣和XXX Y倍役满 ZZZZ点！ [东/南X局][牌谱链接]
XXX自摸 Y倍役满 ZZZ-ZZZZ点/ZZZZ点ALL！ [东/南X局][牌谱链接]
然后大家就可以点进去欣赏狗叫了

**Comment by SAPikachu** [comment]
我后面看看，不过个人不太喜欢滚动，感觉太碍眼，我大概会放到个新的子页面里面。

**Comment by CXY1999** [comment]
可以考虑做个近期役满也行……不过按照雀魂四玉出役满的速度……感觉不是很多

**Comment by SAPikachu** [comment]
刚刚更新了~
