### ISSUE TITLE
金场和三麻

### ISSUE THREAD

**Issue by kamicloud** [SAPikachu/amae-koromo#17]
现在金场和三麻雀士远远超过四麻玉桌，是否可以增加金场和三麻的牌谱？

**Comment by SAPikachu** [comment]
金場因爲數據量太大，除非有人能贊助一台大容量服務器，不然我這邊基本是不會弄了。三麻的話需要修改部分代碼，要等我有空才能做。

**Comment by kamicloud** [comment]
如果保存所有牌谱，存储确实是个问题。不过我觉得没必要保存金场的牌谱，或者只保留近期的牌谱就足够了。

金场相对玉场水平分布不均，所以波动会很频繁，而且大部分没有分析金场对战的需求，只会关心综合数据。只需要保存雀士总体数据，每局增量更新就可以了，这样存储量是有限的。您没有时间弄的话，我会按这个思路尝试下。

**Comment by SAPikachu** [comment]
嗯，加油~有需要的話我可以把我現在用的記錄代碼給你，這樣可能會簡單點

**Comment by kamicloud** [comment]
方便的话真是太感谢您了，有参考可以省去很多调雀魂接口的时间

**Comment by kamicloud** [comment]
最近沉迷领地人生，雀魂先鸽一段时间吧，等有空再弄

**Comment by SAPikachu** [comment]
这两天有点忙，等过完这段时间我先发上去好了~

**Comment by SAPikachu** [comment]
刚刚传到新 repo 了： https://github.com/SAPikachu/amae-koromo-scripts
