### ISSUE TITLE
请问能放出抓数据部分的代码吗？

### ISSUE THREAD

**Issue by Sora233** [SAPikachu/amae-koromo#18]
想要学习下，期待回复。

**Comment by SAPikachu** [comment]
这两天有点忙，过完这段时间我发一下~

**Comment by CXY1999** [comment]
同求 
E-mail:896269291@qq.com

**Comment by SAPikachu** [comment]
刚刚传到新 repo 了： https://github.com/SAPikachu/amae-koromo-scripts
