### ISSUE TITLE
役种统计没有四杠子

### ISSUE THREAD

**Issue by CXY1999** [SAPikachu/amae-koromo#19]
不知道是不是没有人和出来过，感觉可能是漏了

**Comment by SAPikachu** [comment]
应该是没有人和出过，数据库没有记录

**Comment by CXY1999** [comment]
那也应该加上吧 没和出来不等于没有……

**Comment by SAPikachu** [comment]
做起来有点麻烦，所以（

**Comment by paulzzh** [comment]
19-12-17 15:28
[金之间三人南]
@太阳家的猫 刚刚被炸庄!卧槽还是个役满！！16000点! 自摸者:@KNedwin
🀝 🀆🀆🀆🀆 🀠🀠🀠🀠 🀫🀒🀒🀫 🀫🀕🀕🀫 🀝
ドラ:🀃🀟🀄🀞🀐
四杠子 13番
役满 24000点
牌谱: https://www.majsoul.com/1/?paipu=191217-aeaf337b-86d4-42db-bf88-da2f08e60e78

**Comment by SAPikachu** [comment]
金和三麻这边是没有记录的
