### ISSUE TITLE
关于总安定段位计算的问题

### ISSUE THREAD

**Issue by zxyxpxp123** [SAPikachu/amae-koromo#22]
![image](https://user-images.githubusercontent.com/60008604/72624635-47b81700-3982-11ea-8e09-e0ec835510ac.png)
![image](https://user-images.githubusercontent.com/60008604/72624660-4edf2500-3982-11ea-9f8d-d2dc26fdab14.png)
![image](https://user-images.githubusercontent.com/60008604/72624686-58688d00-3982-11ea-84c1-983a52f9ad8e.png)
总安定段位小于玉间安定段位和王座安定段位的任一值，是因为计算总安定段位是按照玉安定段位来的吗？

**Comment by SAPikachu** [comment]
总安定段位包含玉和王座的对局，然后奖励分按玉场算。这情况应该是因为王座的对局一位率较低四位率较高，然后王座的奖励分比玉场高，所以按玉场奖励分算的话会拉低安定段位。

**Comment by zxyxpxp123** [comment]
那能否做到总安定段位分成玉间和王座进行计算再综合，或者按王座和玉的加权平均值计算呢？

**Comment by SAPikachu** [comment]
实现起来有点麻烦，而且个人认为浮动奖励分的话横向比较会更加不准确，所以我不太倾向这样弄。

另外我上面说漏一点，上了魂天之后总安定段位就会按照王座计算了。

**Comment by SAPikachu** [comment]
因为计算方式不明确，总安定段位已经取消，目前需要选择单独等级才会显示。
