### ISSUE TITLE
立直收支

### ISSUE THREAD

**Issue by btsrkex** [SAPikachu/amae-koromo#24]
好像没有计算立直时他家互相直击的送棒和被自摸的送棒?
这样会导致立直收支的数据不准确吧

**Comment by SAPikachu** [comment]
送棒是有包含在收支计算里面的，具体可以看：
https://github.com/SAPikachu/amae-koromo-couchdb/blob/1dff5afdd5a3fabf03bfba4af0db03de9c309d97/_design/player_extended_stats/views/player_stats/map.js#L136
https://github.com/SAPikachu/amae-koromo-couchdb/blob/1dff5afdd5a3fabf03bfba4af0db03de9c309d97/_design/renderers/views/lib/convert_extended_stats.js#L35

**Comment by btsrkex** [comment]
但是支出的说明和计算都是基于放铳的
立直了不放铳但是被炸/送棒就会导致支出是0
是不是除以未和了局数而不是放铳局数比较好
https://amae-koromo.sapk.ch/player/120105012/2020-02-03/2020-02-03/riichi

这个其他收支里也没有计算被自摸的失点,只有送棒(虽然不知道被自摸失点算在立直收支里合不合适)

**Comment by SAPikachu** [comment]
支出我是参考天凤的，那边也是只算放铳的支出，我的理解是这个数据只统计因为立直无法避铳而造成的支出，没有和了的情况基本属于运气问题，所以排除掉会比较好。
