### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by purerosefallen** [SAPikachu/amae-koromo#29]
I want to make my own instance of this project, but currently lack of documents.
Could you provide a document of how to build this one up? including fetching datas from Majsoul. Thanks!

**Comment by SAPikachu** [comment]
This is just a static site and you can run following commands to build it:
```
npm install
npm run build
```

Requirements:

* Recent Linux distribution
* Node 8+

For data I am using a set of scripts with cronjob to pull and save data, you can check the scripts at https://github.com/SAPikachu/amae-koromo-scripts . Data is saved to a CouchDB server. Past matches can't be fetched from Majsoul server and has to be served from own database.

**Comment by purerosefallen** [comment]
Yeah my problem is that data backend. Lack of documents

**Comment by SAPikachu** [comment]
Well the server configuration is a bit messy and I don't really want to write a detailed post for it.. I would suggest to get started via following rough steps:

1. Setup a CouchDB server
2. Configure cron job to run server script to start saving data to the DB
3. Import design doc to CouchDB (will be published a bit later)
4. API will be exposed as endpoints under `http://couchdb:5984/majsoul/_design/rewrites/_rewrite/api`, set up nginx to proxy API request with authentication header.

**Comment by SAPikachu** [comment]
Closed for inactivity, feel free to reopen if needed.
