### ISSUE TITLE
推荐跳转的时候跳到对应的网页

### ISSUE THREAD

**Issue by reusu** [SAPikachu/amae-koromo#35]
中文情况下跳转maj-soul
日语就跳转mahjongsoul
或者给加一个跳转的URL设置
只用在跳转的URL后加上?paipu=
这样镜像站也能用

**Comment by SAPikachu** [comment]
现在应该已经会根据语言选择相应网站了，如果刚切换语言链接不对的话，试试刷新一下？

**Comment by reusu** [comment]
的确切换语言后须刷新才可以更改链接

**Comment by SAPikachu** [comment]
刚刚更新了一下，现在切换语言之后链接会立刻更新了。
