### ISSUE TITLE
更多玩家数据

### ISSUE THREAD

**Issue by SAPikachu** [SAPikachu/amae-koromo#4]
* 和铳数据
* 安定顺位

**Comment by Pliosauroidea** [comment]
希望能够有和铳率-对局的曲线，均顺-对局的曲线，和每个牌谱中点数-局数的图表（类似雀龙门那种）

**Comment by SAPikachu** [comment]
> 希望能够有和铳率-对局的曲线，均顺-对局的曲线，和每个牌谱中点数-局数的图表（类似雀龙门那种）

这个我要研究一下，计算量比较大不知道服务器能不能承受。先转移到另外一个 issue 了。

**Comment by SAPikachu** [comment]
和铳数据已实现，安定顺位转移到新 issue。
