### ISSUE TITLE
东场的小bug

### ISSUE THREAD

**Issue by CXY1999** [SAPikachu/amae-koromo#43]
感谢上线东场！以后抓那位呆人就简单多了！
最近役满也有场次选项了！赞爆！
目前有个小bug
360极速浏览器（极速模式，blink内核）
点主页->English->Recent Yakuman->然后再切回中文或者日语，发现场次选项的语言没变，还是英文
点主页->日本语->最近役满->然后切回其它语言，只有南场场次选项语言变了，排在后面的东场仍然是繁体日语。
点主页->中文 ->最近役满->切回其它语言，没有发现任何问题
而且测了几次都可以复现。
暂不知道对于其它浏览器内核 包括安卓浏览器，是否可以复现。

**Comment by SAPikachu** [comment]
感谢报告~刚刚推送了更新，等代码刷新之后应该就会修复了，麻烦确认一下？

**Comment by CXY1999** [comment]
嗯，我一会多开几种浏览器确认一下。
