### ISSUE TITLE
来点麻将统计学？

### ISSUE THREAD

**Issue by QiushiZhu** [SAPikachu/amae-koromo#49]
现在的牌谱屋虽然收集了数据，但有效的分析不太够。
比如各种牌（字/19/37...)在不同情况下（现张数/DORA/筋/早外/巡目）的和率/铳率，这种能帮人改善雀力的数据。
举个例子，我想知道各种条件完全一样的3456m一定要打一张，那哪张会比较好，体感3m更容易铳，而这个体感是否能被验证。当听牌家早巡切了4m，是否又是3m更安全等等
思考了一下，做一定的简化后（即不是严格的和率/铳率，只做横向对比）这个数据甚至可以和麻将逻辑无关，直接提取json中点炮的那一张的信息，再转sql就很好查。
差不多这种结构：
index   char    is_zimo is_dora turn    points  num jin_type    bi_type 
12345  3m     0          0            9         3900    0      2               0         
我一直在从事类似的工作，大佬如果感兴趣但没时间的话也可以collaborate

**Comment by SAPikachu** [comment]
这个我确实最近没什么精力去弄…如果有需要的话我可以提供我收集到的所有原始牌谱数据给你分析，怎么样呢？

**Comment by QiushiZhu** [comment]
可以啊，怎么传资料？我的邮箱是151452226@qq.com或者a5530880@gmail.com

**Comment by SAPikachu** [comment]
刚刚发过去了~
