### ISSUE TITLE
每次重新选择同一个之前搜索过的时间范围后网站重新搜索一次对战数据库是对服务器压力很大吗？

### ISSUE THREAD

**Issue by AragakiSena** [SAPikachu/amae-koromo#55]
情况是这样，我昨晚半夜（已过0点）一边打的时候，一边搜索了一次7/1-8/8的对局记录，搜出来的结果是49局。然后我打完最后一局，今天早上再来搜索同一个时间段的记录，仍是49局。然后我改搜之前没搜过的7/2-8/8之后则是50局。结合平常用的时候网站的一些表现效果来看，应该是曾经搜索过的时间段，搜索结果直接进缓存了，下次再搜的时候就直接拉缓存结果是吗？那这个缓存结果有效期是多久。这么设置是担心服务器搜索压力过大吗？还有我之前提的希望能按最近N场来搜索的功能，是不是也是因为这个原因所以还没搞好。

**Comment by SAPikachu** [comment]
对的，目前缓存的时间设置得比较长以减轻服务器压力，最长应该一天左右过期。不过功能没有加倒不是因为这个，主要是最近事情实在太多没精力弄新功能…
