### ISSUE TITLE
魂天和雀圣的王座安定段位应该用相同的公式

### ISSUE THREAD

**Issue by lixiaoms** [SAPikachu/amae-koromo#56]
现在的魂天和雀圣计算王座安定段位的公式不一样，我认为这不合适。主要有两点：
1、按现在这个+50 +20 -20 -50公式计算的魂天的王座安定段位意义不大，因为只要是大于0就代表安定正无穷，小于0就代表安定掉出魂天。
2、按照原来的公式才能对雀圣和魂天的实力做出对比，安定段位排行榜才有意义。不然一个在王座平均水平的玩家，雀圣显示安定豪二，魂天却显示安定魂天+0。一个在王座很少吃四的玩家，雀圣显示安定魂天+几百，魂天却显示安定魂天+几十。
3、数据中的分数期望足够表示魂天在王座的安定情况了，不需要现在的这个没有意义的安定公式。而且官方有可能会对50 20 -20 -50进行调整。

因此，我建议改回原来的安定段位计算公式。

**Comment by SAPikachu** [comment]
目前如果雀圣在王座能安魂的话就会用魂天的分数期望计算，如果有哪个玩家不是这样的话那说明代码有问题需要修复，可以提供一下玩家的URL吗？另外如果魂天分数期望是负值的话安定段位是会回退到圣或者以下的。

> 3、数据中的分数期望足够表示魂天在王座的安定情况了，不需要现在的这个没有意义的安定公式。而且官方有可能会对50 20 -20 -50进行调整。
因为魂天的分数系统和雀圣完全不一样，目前的安定段位算法确实是一个妥协，但是我也不认为应该直接使用以前的算法，因为安定段位本身是为了表示按照当前数据最终可以稳定的段位，以现在的系统只要魂天分数期望是正数那必定安正无穷，那以前的算法会造成混乱。以前的安定段位其实核心也是分数期望，只是换算成了一个更容易理解的数字而已。

> 按照原来的公式才能对雀圣和魂天的实力做出对比，安定段位排行榜才有意义。
玉的安定段位以及排行榜是按照以前的公式计算的，只是不再显示魂。王座的排行榜我也同意无法完全反映玩家的实力，但是因为在新系统下魂天的有利打法本身就和雀圣有差异（魂天更偏向进攻），个人认为以安定段位本身的定义（甚至是所有以得分为基础的算法）不可能很好地比较两种打法的实力差别。目前的排行榜只是留作参考之用，如果后面造成太多误解的话我个人会考虑取消。

**Comment by lixiaoms** [comment]
感谢您的解释。我也同意暂时取消安定段位的排行，留下平均顺位的排行。
但是我还是不太清楚您说的"雀圣在王座能安魂的话就会用魂天的分数期望计算"这件事，因为把鼠标放在安定段位上时，雀圣和魂天显示的计算方法是不一样的。虽然目前我按50 20 -20 -50来算也对不上魂天的数据，您是否能检查一下。

**Comment by SAPikachu** [comment]
可以提供下玩家ID吗？我确认下代码有没有问题

**Comment by lixiaoms** [comment]
我随便在首页看的
比如这个ID https://amae-koromo.sapk.ch/player/461256/16 把鼠标放在放在安定段位上时，显示的还是以前的安定段计算公式
又比如这个魂天 https://amae-koromo.sapk.ch/player/97200/16 我按50 20 -20 -50算不出5.83这个值

**Comment by SAPikachu** [comment]
感谢，我晚点看看

**Comment by SAPikachu** [comment]
我刚刚算了一下，这两位的分数期望看起来都是正确的，比如说 https://amae-koromo.sapk.ch/player/97200/16 现在网页上显示是5.86，手动计算：

```
50 * 30.75% + 20 * 26.63% + -20 * 21.55% + -50＊21.07% = 5.856
```

和显示的一致。你是用什么算法计算的呢？

**Comment by lixiaoms** [comment]
> 我刚刚算了一下，这两位的分数期望看起来都是正确的，比如说 https://amae-koromo.sapk.ch/player/97200/16 现在网页上显示是5.86，手动计算：
> 
> ```
> 50 * 30.75% + 20 * 26.63% + -20 * 21.55% + -50＊21.07% = 5.856
> ```
> 
> 和显示的一致。你是用什么算法计算的呢？



> 我刚刚算了一下，这两位的分数期望看起来都是正确的，比如说 https://amae-koromo.sapk.ch/player/97200/16 现在网页上显示是5.86，手动计算：
> 
> ```
> 50 * 30.75% + 20 * 26.63% + -20 * 21.55% + -50＊21.07% = 5.856
> ```
> 
> 和显示的一致。你是用什么算法计算的呢？



> 我刚刚算了一下，这两位的分数期望看起来都是正确的，比如说 https://amae-koromo.sapk.ch/player/97200/16 现在网页上显示是5.86，手动计算：
> 
> ```
> 50 * 30.75% + 20 * 26.63% + -20 * 21.55% + -50＊21.07% = 5.856
> ```
> 
> 和显示的一致。你是用什么算法计算的呢？

**Comment by lixiaoms** [comment]
嗯 是的 我被雀圣显示的那个计算规则误导了公式。确实现在显示的数值都没问题
