### ISSUE TITLE
魂天掉雀圣后显示的安定段位存在问题

### ISSUE THREAD

**Issue by lixiaoms** [SAPikachu/amae-koromo#58]
https://amae-koromo.sapk.ch/player/69520294/16
排行榜上的这人安定段位直接使用了其得点效率作为安定段位，这只对魂天才成立的，然而系统没有识别到这人已经掉段为雀圣了。
另外，这人的得点效率的46.30也和其各顺位比例对不上号，请检查一下。

**Comment by SAPikachu** [comment]
感谢报告，稍后我检查下代码。

**Comment by SAPikachu** [comment]
刚刚修复了。
