### ISSUE TITLE
Missing match data

### ISSUE THREAD

**Issue by limgit** [SAPikachu/amae-koromo#67]
I've found some match data is missing

ex)

There are matches for 1/4, 1/5, and 1/7, but not 1/6

However, from my game log, there is a match for 1/6

**Comment by limgit** [comment]
nvm. I've found the message

> This is a fan site, data accuracy can't be fully guaranteed

**Comment by SAPikachu** [comment]
The watch feature in Majsoul sometimes misses a few matches, which prevents my server from logging it. If you can provide link of the missing match, I can manually import it. :)

**Comment by limgit** [comment]
The following match is missed: `https://game.mahjongsoul.com/?paipu=220106-dd1875b3-d5fc-45dc-bf70-aced04550f1a_a431137230`

Thanks!

**Comment by SAPikachu** [comment]
Got it and added the match to the queue, it should appear on the website in an hour (let me know if it don't). :)

**Comment by limgit** [comment]
I can see the game now. Thanks!
