### ISSUE TITLE
提个问题可不可以用爬虫只收集自己个人段位赛数据

### ISSUE THREAD

**Issue by brqs** [SAPikachu/amae-koromo#74]

**Comment by SAPikachu** [comment]
理论上是可以，有 API 可以获取自己的牌谱列表。另外你可以试试另外一个工具 https://bbs.nga.cn/read.php?tid=17007935 ，原理不太一样不过也可以用来分析自己的牌谱。

**Comment by brqs** [comment]
我是雀魂新手，想收集数据记录自己的雀魂生涯放到我自己的网站做记录用，就类似这种https://amae-koromo.sapk.ch/player/16000797/12，我现在采取的方法是用excl手动记录然后转换十分的不智能（）

**Comment by SAPikachu** [comment]
不好意思，我不太明白你需要什么。具体的代码我没办法帮你写，不过你可以考虑用 Chrome 的开发者工具查看 API 的网络请求，然后在你的网站调用合适的 API 获取需要的数据。

**Comment by brqs** [comment]
我在自己做了，谢谢大佬的帮助qaq
