### ISSUE TITLE
四麻漏谱了

### ISSUE THREAD

**Issue by huhaoo** [SAPikachu/amae-koromo#76]
https://amae-koromo.sapk.ch/player/8828954/9 2022.3.20 14:41只显示了两个谱，漏掉了更早打的 雀魂牌谱:https://game.maj-soul.com/1/?paipu=220320-4c2eb47d-ca2b-411d-9462-bd7bae090fca_a116938075

**Comment by SAPikachu** [comment]
感谢报告，这个谱已经在系统里面了，大概几个小时内就会显示。如果一天之后还是没有显示的话麻烦再告诉一下，谢谢。
