### ISSUE TITLE
对战记录遗漏

### ISSUE THREAD

**Issue by KiraYo4kage** [SAPikachu/amae-koromo#78]
四麻玉间，打一天发现漏了一局，雀魂游戏内是有记录的。
是因为缓存原因这一局还没显示出来吗，以后会自动补上么。
想起来以前也经常有这个问题，来发个issue问下。
牌谱链接：https://game.maj-soul.com/1/?paipu=jkjoom-yts5yy4a-5487-6995-idab-mdihismnovnr_a12260298_2

**Comment by SAPikachu** [comment]
因为观战 API 有时候是会漏掉一些对局，这边没办法获取就会出现遗漏。如果对局后 24 小时都没有显示那多半就是这个原因，把遗漏的牌谱连接发给我就可以人工添加了。这一局已经添加到处理队列了，麻烦稍后确认，谢谢。

**Comment by KiraYo4kage** [comment]
> 

现在已经加上了，谢谢回复。
