### ISSUE TITLE
[BUG] 在不同场次渡劫，刚刚升段的玩家，升段分数期望计算出错

### ISSUE THREAD

**Issue by 17876zjc** [SAPikachu/amae-koromo#80]
我水表我自己的时候发现的：https://ikeda.sapk.ch/player/1083020/26
我在王座打到离圣二差110分的时候去玉之间渡劫，现在段位是圣二3000/6000。但是在选中“王座”搜索时，升段分数期望依然被计算为110/9.6（得分期望) = 11，而不是按照圣二升圣三的3000/9.6计算

![(5SX J0}`_7@D_DZDKS~JB8](https://user-images.githubusercontent.com/35091817/170457887-7bb5bfa9-2857-407c-8a96-79e0bc2c2803.png)

![`RE)BDG X{K$0CFZ0L2(F@X](https://user-images.githubusercontent.com/35091817/170457913-193e1d90-dd64-44d5-a618-644d25465862.png)

**Comment by SAPikachu** [comment]
感谢报告，我明天看看能不能修复
