### ISSUE TITLE
牌谱屋收藏按钮消失

### ISSUE THREAD

**Issue by Pliosauroidea** [SAPikachu/amae-koromo#82]
我记得牌谱屋之前有个收藏/关注玩家的选项.现在进去之后找不到了
是这个功能被移除了么,还是说我这边的加载问题
![image](https://user-images.githubusercontent.com/37920182/182126244-3fafd9b8-23bb-496e-adaf-55467ff1d7b0.png)
↑没有收藏按钮的牌谱屋界面

**Comment by SAPikachu** [comment]
如果没有收藏任何玩家的话，导航栏右上的收藏列表不会显示。打开任意玩家页面应该就可以看到收藏按钮。

**Comment by Pliosauroidea** [comment]
按照对应方法确实出现了,但是之前收藏过很多玩家,最近打开都消失了,可能是在我无意识的时候清了cookie之类吧
