### ISSUE TITLE
记录场数缺失

### ISSUE THREAD

**Issue by jovensun** [SAPikachu/amae-koromo#87]
开发者，你好。本人昨晚升的雀杰，今天开始打金之间，一天打了13把四人南，但是只记录了10把。
一开始以为是还没更新，但是发现新打的都记录了，更早打的竟然没有记录，这是怎么回事呢？ 

如下图：通过时间可以看到，晚上21点后，我总共打了4把，但是只记录了一把，更诡异的是 早打的没记录上，晚打的反而记录了。

![牌谱屋记录场数问题](https://user-images.githubusercontent.com/19667184/200127497-b6d05e4b-cc19-4a01-a13f-421ea9f381be.png)

**Comment by SAPikachu** [comment]
你好，牌譜更新順序不對是正常現象，麻煩現在再看看還有沒有缺失？如果還有的話，麻煩貼一下缺少的牌譜鏈接？

**Comment by jovensun** [comment]
> 你好，牌譜更新順序不對是正常現象，麻煩現在再看看還有沒有缺失？如果還有的話，麻煩貼一下缺少的牌譜鏈接？

謝謝您，睡了一觉现在有了，十分感谢您开发此工具。
