### ISSUE TITLE
总用户数量变化趋势

### ISSUE THREAD

**Issue by luang008** [SAPikachu/amae-koromo#89]
你好，
我的想法是如果statistics/num-player-stats的数据以往每次更新时都有备份的话，应该可以画出一个总用户数量随时间变化的趋势图。就是不知道这个数据有没有一直备份，不知道有没有可能backfill。
谢谢

**Comment by SAPikachu** [comment]
不好意思，這個沒有做歷史備份呢。

**Comment by luang008** [comment]
好的 谢谢
