### ISSUE TITLE
牌谱指向的连接不正确

### ISSUE THREAD

**Issue by Pliosauroidea** [SAPikachu/amae-koromo#91]
点击牌谱屋中的牌谱,连接为`game.maj-soul.net/xxxx`,无法正确打开牌谱(如https://game.maj-soul.net/1/?paipu=230105-4617b239-a471-49af-b6c0-9f6c52601f9c_a90119750)
可能的正确连接应为.com域名(如https://game.maj-soul.com/1/?paipu=230105-4617b239-a471-49af-b6c0-9f6c52601f9c_a90119750)

复现方法:点击任意牌谱,无法打开对应界面

**Comment by SAPikachu** [comment]
感謝報告，修復稍後就會推送。

Fixed in b373a02
