### ISSUE TITLE
根据昵称查找玩家时，不同服务器的同名玩家只能找到其中一个

### ISSUE THREAD

**Issue by BlueNoBaka** [SAPikachu/amae-koromo#98]
今天改了个名才发现不同服务器的玩家可以重名，但牌谱屋的查找结果只会显示其中一个玩家。
昵称同为 `中川菜々` ，目前只能通过昵称搜到日服这位的页面。

我在中文服的页面：
https://amae-koromo.sapk.ch/player/20092
日服同名玩家的页面：
https://ikeda.sapk.ch/player/71374919

**Comment by SAPikachu** [comment]
這個似乎是緩存問題，稍後等緩存過期就會回復正常了。

**Comment by BlueNoBaka** [comment]
确实，现在已经能正常搜到了，感谢解答。
