### ISSUE TITLE
请问目前牌谱屋数据是不直接提供对局uuid了吗

### ISSUE THREAD

**Issue by teble** [SAPikachu/amae-koromo#99]
如题，我看目前都是通过API根据_id重定向到雀魂对应的牌谱链接了，这是出于什么考量吗

**Comment by SAPikachu** [comment]
因为一些暂时不太想公开谈论的原因，这边不想牌谱屋再继续大规模公开牌谱 ID ，所以加上了防爬的措施。

**Comment by teble** [comment]
好的，感谢解答
